version: "3.8"
services:
  bot:
    build:
      context: ./bot
      args:
        GO_VERSION: "1.17"
    container_name: bot
    working_dir: /opt/app/bot
    env_file: .env
    volumes:
      - ./bot:/opt/app/bot
  clasp:
    build:
      context: ./clasp
      args:
        NODE_VERSION: "16.13"
    container_name: clasp
    working_dir: /opt/app/clasp
    env_file: .env
    volumes:
      - ./clasp:/opt/app/clasp
      - node_module-volume:/opt/app/clasp/node_modules/
      - clasprc-json:/root/.clasprc.json
  db:
    build: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
    tty: true

volumes:
  postgresql-data: null
  node_module-volume: null
  clasprc-json: null
