services:
  app:
    build:
      args:
        GO_VERSION: "1.22.3"
    container_name: app
    working_dir: /opt/app
    env_file: .env
    secrets:
      - google_secrets
    volumes:
      - .:/opt/app
      - golang-data:/go
    networks:
      - sfs-network
    depends_on:
      - db
  db:
    image: mariadb
    container_name: mariadb
    env_file: .env
    environment:
      - MARIADB_USER=${DBUSER}
      - MARIADB_PASSWORD=${DBPASSWORD}
      - MARIADB_DATABASE=sfs
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    tty: true
    networks:
      - sfs-network

volumes:
  mariadb-data: null
  golang-data: null

networks:
  sfs-network:

secrets:
  google_secret:
    file: secrets/credentials.json
