version: "3.8"
services:
  app:
    build:
      target: production
      args:
        GO_VERSION: "1.19.5"
    container_name: app
    working_dir: /opt/app
    env_file: .env
    environment:
      - PGPASSWORD=password
      - PGUSER=postgres
      - PGSSLMODE=disable
      - PGHOST=postgres
      - APP_ENV=develop
    volumes:
      - .:/opt/app
      - golang-data:/go
    networks:
      - sfs-network
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
      - ./db/init:/docker-entrypoint-initdb.d
    tty: true
    networks:
      - sfs-network

volumes:
  postgresql-data: null
  golang-data: null

networks:
  sfs-network:
