version: "3.8"
services:
  bot:
    build:
      context: ./bot
      target: production
      args:
        GO_VERSION: "1.18.3"
    container_name: bot
    working_dir: /opt/app/bot
    env_file: .env
    environment:
      - PGPASSWORD=password
      - PGUSER=postgres
      - PGSSLMODE=disable
      - PGHOST=postgres
      - APP_ENV=develop
    volumes:
      - ./bot:/opt/app/bot
    networks:
      - sfs-network
    depends_on:
      - db
  clasp:
    build:
      context: ./clasp
      args:
        NODE_VERSION: "16.13"
    container_name: clasp
    working_dir: /opt/app/clasp
    env_file: .env
    volumes:
      - ./clasp:/opt/app/clasp
      - node_module-volume:/opt/app/clasp/node_modules/
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
      - ./bot/db/init:/docker-entrypoint-initdb.d
    tty: true
    networks:
      - sfs-network

volumes:
  postgresql-data: null
  node_module-volume: null

networks:
  sfs-network:
