// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"time"
)

type Guild struct {
	ID        int64
	Name      string
	DiscordID string
}

type SystemUser struct {
	ID        int64
	DiscordID string
}

type SystemUserGuild struct {
	SystemUserID int64
	GuildID      int64
}

type Token struct {
	ID           int64
	SystemUserID int64
	AccessToken  string
	TokenType    string
	RefreshToken string
	Expiry       time.Time
}
