// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"time"
)

type Guild struct {
	ID        int64
	Name      string
	DiscordID string
	SheetID   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SystemUser struct {
	ID        int64
	DiscordID string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SystemUserGuild struct {
	SystemUserID int64
	GuildID      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Token struct {
	ID           int64
	SystemUserID sql.NullInt64
	GuildID      sql.NullInt64
	AccessToken  sql.NullString
	TokenType    string
	RefreshToken string
	Expiry       time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
